### ISSUE TITLE
Output pin showing used antenna

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/SiK#8]
For a quick analysis of the condition of the antennas (and their connection), it would be useful to be able to connect an LED that would signal the used antenna. Signal for switching of the switch cannot be used for this, because it switches very often (even for finding a better antenna). So it switches antennas even if only one antenna is actually used. 

Therefore it would be great to have an output that is high/low depending on which antenna is actually used. 

This feature would require, I suppose, FW modification, right? @povik 

The processor output is very strong. Therefore, it is not a problem to connect LED directly to it. 
It would be worth considering to have this LED directly on modem PCB. But for the ground-side modem, it would useful to be able to connect an external LED.

**Comment by kaklik** [comment]
According to a discussion with @povik  the correct location to implement the selected antenna indication is in this [code block](https://github.com/ThunderFly-aerospace/SiK/blob/feac1e63b5624ca153c157014ab928b417badf3d/Firmware/radio/radio_446x.c#L1039-L1040C7).

But the GPIO_x_CONFIG are macros defined for specific HW boards. They could handle ant1 and ant2 state variables. That solution is needed to save memory space.

**Comment by kaklik** [comment]
I modified the firmware, but the selected antenna indicator does not work as could be expected. 

https://github.com/ThunderFly-aerospace/SiK/assets/1194177/d4665f0e-8ef9-4309-9156-773f3b32f411

If there is antenna connected to the bottom port (on the video). The antenna indicator D1 is completely off (which seems to be correct). But in case where I reconnect the same antenna to the upper port, the LED starts blinking. The expected behavior is to light on completely or almost completely.
